### ISSUE TITLE
Can you add support for more input gestures?

### ISSUE THREAD

**Issue by ScottChesworth** [Kostya-Gladkiy/WhatsAppPlus#4]
It would be super useful if the keystrokes could be adjusted in NVDA/Preferences/Input Gestures. Do you have any plans to support that?

**Comment by Kostya-Gladkiy** [comment]
Hello! Almost all keyboard shortcuts for whatsAppPlus and unigramPlus can be changed in NVDA input gestures.Надіслано з програми Пошта для Windows Від: ScottChesworthНадіслано: 17 червня 2023 р. о 1:32Кому: Kostya-Gladkiy/WhatsAppPlusКопія: SubscribedТема: [Kostya-Gladkiy/WhatsAppPlus] Can you add support for more input gestures? (Issue #4) It would be super useful if the keystrokes could be adjusted in NVDA/Preferences/Input Gestures. Do you have any plans to support that?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ScottChesworth** [comment]
Really? Running version 1.9.0 of WhatsAppPlus here, I only have one entry visible in Input Gestures: "Open WhatsAppPlus settings window".

**Comment by Kostya-Gladkiy** [comment]
In order for the input gestures to display all key combinations, you need to open WhatsApp and then open the NVDA input gestures.Надіслано з програми Пошта для Windows Від: ScottChesworthНадіслано: 17 червня 2023 р. о 15:01Кому: Kostya-Gladkiy/WhatsAppPlusКопія: Kostya-Gladkiy; CommentТема: Re: [Kostya-Gladkiy/WhatsAppPlus] Can you add support for more input gestures? (Issue #4) Really? Running version 1.9.0 of WhatsAppPlus here, I only have one entry visible in Input Gestures: "Open WhatsAppPlus settings window".—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ScottChesworth** [comment]
Got it, thanks! Somehow I didn't think to check whether having WhatsApp in focus would make a difference. This is excellent, everything I was hoping would be assignable is here. :)
